name: CI

on: [push]

jobs:
    build_and_test:
        name: Build, lint, and test
        runs-on: ubuntu-latest
        # run tests in rai-python container at
        container:
          image: docker.pkg.github.com/ischubert/rai-python/rai-python:plan_conditioned_rl
          credentials:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
          HOME: /root
        steps:
        - name: Checkout repo
          uses: actions/checkout@v2 # checks out repo and downloads it to runner
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Build and install gym-physx
          run: |
            pip install .
        - name: Lint with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        - name: Test with pytest
          run: |
            pytest
